basic_settings:
  site_title: SimpleSportsCaster
  company_name: Zofware LLC
  site_tagline: Stream and record your games with a live scoreboard
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/avatar.jpg
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'About'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Privacy Policy'
      url: '/privacypolicy'
    - title: 'Terms of Use'
      url: '/termsofuse'
#    - title: 'Projects'
#      url: '/projects/'
    - title: 'Help'
      url: '/help'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/info@simplesportscaster.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

# Social icons from FontAwesome
# By default, brand icons (fab) are used.
# Prefix with fas_ to use solid icons (e.g. fas_rss_url: 'https://your.feed.xml')
# https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
# https://fontawesome.com/icons?d=gallery&m=free
social_settings:
  microsoft_url: 'https://www.microsoft.com/store/apps/9NRQMTPGS298'
  facebook_url: ''
  twitter_url: 'https://twitter.com/zofware'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/channel/UCgpd1uSxhDBEaVLVdVEelXQ'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''
  fas_rss_url: 'https://www.simplesportscaster.com/feed.xml'

color_settings:
  background_color: '#ffffff'          # white
  background_alt_color: '#f4f5f6'      # almost white
  text_dark_color: '#1C5278'           # darker business card blue
  text_medium_color: '#266DA0'         # business card blue
  text_light_color: '#308BCC'          # lighter business card blue
  accent_color: '#29894A'              # dark green
  border_color: '#266DA0'              # business card blue
  overlay_background_color: '#161B21'  # very dark blue-gray
  overlay_text_color: '#ffffff'        # white
  error_color: '#D64541'               # medium red

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  title_font: '"Nunito", sans-serif'
  body_font: '"Nunito", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 19
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
