basic_settings:
  site_title: SimpleSportsCaster
  company_name: Zofware LLC
  site_tagline: Stream and record your games with a live scoreboard
  favicon_image: /images/favicon.png
  current_build: 219

header_settings:
  avatar_image: 
  logo_image: /images/logo-banner-with-shadow-1024.png
  logo_width: 1024

menu_settings:
  menu_items:
    - title: 'About'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Privacy Policy'
      url: '/privacypolicy'
    - title: 'Terms of Use'
      url: '/termsofuse'
    - title: 'Projects'
      url: '/projects/'
    - title: 'History'
      url: '/releases'
    - title: 'Help'
      url: '/help'
    - title: 'Forum'
      url: 'https://github.com/Zofware/SimpleSportsCaster/discussions'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/info@simplesportscaster.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

# Social icons from FontAwesome
# By default, brand icons (fab) are used.
# Prefix with fas_ to use solid icons (e.g. fas_rss_url: 'https://your.feed.xml')
# https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
# https://fontawesome.com/icons?d=gallery&m=free
social_settings:
  Microsoft_url: 'https://www.microsoft.com/store/apps/9NRQMTPGS298?cid=sscdotcom'
  Facebook_url: ''
  Twitter_url: 'https://twitter.com/zofware'
  Instagram_url: ''
  Snapchat_url: ''
  YouTube_url: 'https://www.youtube.com/@simplesportscaster'
  google-plus_url: ''
  Vimeo_url: ''
  Pinterest_url: ''
  Medium_url: ''
  Quora_url: ''
  Amazon_url: ''
  Apple_url: ''
  Android_url: ''
  Tumblr_url: ''
  Dribbble_url: ''
  Behance_url: ''
  DeviantArt_url: ''
  GitHub_url: 'https://github.com/Zofware/SimpleSportsCaster'
  Reddit_url: ''
  Flickr_url: ''
  Etsy_url: ''
  Kickstarter_url: ''
  SoundCloud_url: ''
  Spotify_url: ''
  Bandcamp_url: ''
  LinkedIn_url: ''
  fas_RSS_url: 'https://www.simplesportscaster.com/feed.xml'

color_settings:
  background_color: '#ffffff'          # background color for all pages         white
  background_alt_color: '#f4f5f6'      # contact form background                almost white
  text_dark_color: '#045FA4'           # title, heading, and link text          darker than logo blue
  text_medium_color: '#000000'         # normal body text                       black
  text_light_color: '#0482E4'          # footer, social icons, dates            logo blue
  accent_color: '#0482E4'              # link underlines and hover highlights   logo blue
  border_color: '#045FA4'              # text entry box border                  darker than logo blue
  overlay_background_color: '#161B21'  # not used                               very dark blue-gray
  overlay_text_color: '#ffffff'        # not used                               white
  error_color: '#D64541'               # ???                                    medium red

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=News+Cycle:300,400,400i,600" rel="stylesheet">'
  title_font: '"News+Cycle", sans-serif'
  body_font: '"News+Cycle", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 20
    medium_size: 22
    large_size: 24
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 19
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  # unfortunately ajax_loading interferes with Disqus
  ajax_loading: false
  analytics_code: false
  custom_styles: "/css/build-dependent-content.css"
  header_js: false
  footer_js: "/js/build-dependent-content.js"
