site: SimpleSportsCaster
title: SimpleSportsCaster

url: https://www.simplesportscaster.com
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  help:
    output: true
    permalink: /help/:slug
  future:
    output: true
    permalink: /future/:slug
  releases:
    output: true
    permalink: /releases/:slug
  redirects:
    output: true
    permalink: /redirects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      min_build: 0
      max_build: 999999
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

timezone: America/Los_Angeles

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-archives

paginate: 6
paginate_path: "/blog/page:num/"

liquid:
    error_mode:       warn
    strict_filters:   true
    strict_variables: false

feed:
  collections:
    - releases

jekyll-archives:
  enabled: all
  layouts:
      year: archive-year
      month: archive-month
      day: archive-day
      category: archive-category
      tag: archive-tag
  permalinks:
    year: '/blog/archive/date/:year/'
    month: '/blog/archive/date/:year/:month/'
    day: '/blog/archive/date/:year/:month/:day/'
    tag: '/blog/archive/tag/:name/'
    category: '/blog/archive/category/:name/'

