source 'https://rubygems.org'

gem "github-pages", "~> 219", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

group :jekyll_plugins do
  gem 'activesupport', '>=4.1.11'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jekyll-feed'
  gem 'jekyll-archives'
  gem 'tzinfo'
  gem 'tzinfo-data'
end