source 'https://rubygems.org'

gem "github-pages", "~> 217", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'activesupport', '>=4.1.11'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jekyll-feed'
  gem 'jekyll-archives'
  gem 'tzinfo'
  gem 'tzinfo-data'
end